<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="john-PC" name="nov25.GenerateReports" tests="3" failures="0" timestamp="25 Nov 2019 08:02:09 GMT" time="3.650" errors="1">
  <testcase name="TC2" time="3.126" classname="nov25.GenerateReports">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method nov25.GenerateReports.TC2() didn&#039;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method nov25.GenerateReports.TC2() didn't finish within the time-out 3000
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1154)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- TC2 -->
  <testcase name="TC1" time="0.448" classname="nov25.GenerateReports"/>
  <testcase name="TC3" time="0.076" classname="nov25.GenerateReports">
    <skipped/>
  </testcase> <!-- TC3 -->
</testsuite> <!-- nov25.GenerateReports -->
